"""A compact high-frequency English content vocabulary for the KGW
greenlist marker.

Used by the end-to-end proof: when a foreign model's token is not in the
greenlist, the marker substitutes a green word from this pool. It is a
frequency vocabulary, NOT a synonym table — the substitution carries the
greenlist signal without pretending to preserve exact nuance. This is the
honest text-only approximation of token-sampling watermarking.

Kept deliberately compact (a few hundred high-frequency content words) so it
stays dependency-free and auditable.
"""

# High-frequency English content words (nouns/verbs/adjectives/adverbs),
# each with a short list of interchangeable near-synonyms or same-class
# words drawn from the same frequency band. Entries are grouped so the
# marker can pick a green alternative.
FREQUENT_VOCAB: dict[str, list[str]] = {
    "people": ["individuals", "persons", "humans", "citizens", "folks"],
    "time": ["period", "moment", "duration", "era", "interval"],
    "year": ["decade", "era", "period", "cycle"],
    "way": ["method", "approach", "manner", "route", "path", "means"],
    "day": ["date", "period", "stretch", "window"],
    "thing": ["object", "item", "entity", "element", "matter"],
    "man": ["person", "individual", "figure"],
    "woman": ["person", "individual"],
    "life": ["existence", "being", "reality"],
    "world": ["globe", "planet", "earth", "realm", "society"],
    "work": ["labor", "effort", "task", "operation", "job"],
    "system": ["framework", "structure", "scheme", "network", "apparatus"],
    "part": ["piece", "segment", "portion", "section", "component"],
    "place": ["location", "site", "spot", "position", "area"],
    "group": ["set", "cluster", "collection", "cohort", "band"],
    "case": ["instance", "example", "scenario", "situation", "occurrence"],
    "point": ["aspect", "element", "detail", "factor", "facet"],
    "problem": ["issue", "challenge", "difficulty", "obstacle", "concern"],
    "fact": ["truth", "reality", "datum", "observation"],
    "question": ["query", "inquiry", "issue", "matter", "topic"],
    "result": ["outcome", "effect", "consequence", "product", "finding"],
    "change": ["alter", "modify", "shift", "transform", "adjust"],
    "result_alt": ["outcome", "product", "consequence", "effect"],
    "make": ["create", "produce", "build", "generate", "form", "construct"],
    "use": ["employ", "apply", "utilize", "deploy", "adopt", "leverage"],
    "find": ["discover", "locate", "identify", "detect", "uncover"],
    "show": ["reveal", "display", "demonstrate", "illustrate", "indicate"],
    "give": ["provide", "offer", "supply", "deliver", "grant", "furnish"],
    "take": ["grab", "receive", "accept", "obtain", "adopt", "collect"],
    "need": ["require", "demand", "necessitate", "entail"],
    "think": ["consider", "believe", "reason", "judge", "assume", "suppose"],
    "know": ["understand", "recognize", "realize", "grasp", "comprehend"],
    "say": ["state", "declare", "mention", "report", "claim", "assert"],
    "look": ["glance", "examine", "inspect", "observe", "review"],
    "go": ["move", "proceed", "advance", "travel", "depart"],
    "come": ["arrive", "emerge", "appear", "surface", "approach"],
    "get": ["obtain", "acquire", "gain", "receive", "secure"],
    "help": ["assist", "support", "aid", "enable", "facilitate"],
    "start": ["begin", "initiate", "launch", "commence", "kick off"],
    "stop": ["halt", "end", "cease", "terminate", "finish"],
    "keep": ["maintain", "retain", "preserve", "sustain"],
    "see": ["observe", "notice", "witness", "perceive", "spot"],
    "want": ["desire", "seek", "wish", "intend", "aim"],
    "great": ["strong", "major", "considerable", "substantial", "significant"],
    "important": ["crucial", "vital", "essential", "key", "significant"],
    "good": ["solid", "sound", "effective", "strong", "valuable"],
    "bad": ["poor", "weak", "flawed", "inadequate", "problematic"],
    "big": ["large", "substantial", "major", "considerable", "broad"],
    "small": ["tiny", "minor", "limited", "narrow", "modest"],
    "high": ["elevated", "substantial", "significant", "considerable"],
    "low": ["reduced", "limited", "modest", "minimal"],
    "new": ["fresh", "recent", "novel", "modern", "current"],
    "old": ["former", "previous", "ancient", "outdated", "prior"],
    "early": ["initial", "preliminary", "opening", "preceding"],
    "late": ["delayed", "overdue", "belated", "tardy"],
    "fast": ["rapid", "quick", "swift", "speedy", "brisk"],
    "slow": ["gradual", "sluggish", "delayed", "measured"],
    "hard": ["difficult", "challenging", "tough", "demanding"],
    "easy": ["simple", "straightforward", "effortless", "basic"],
    "clear": ["obvious", "evident", "apparent", "plain", "transparent"],
    "strong": ["robust", "powerful", "solid", "substantial"],
    "weak": ["fragile", "frail", "tenuous", "feeble"],
    "more": ["further", "additional", "extra", "greater"],
    "less": ["reduced", "diminished", "lower", "fewer"],
    "many": ["numerous", "countless", "several", "multiple"],
    "few": ["limited", "scarce", "sparse", "rare"],
    "increase": ["raise", "boost", "expand", "grow", "elevate"],
    "reduce": ["lower", "cut", "decrease", "shrink", "diminish"],
    "create": ["generate", "produce", "design", "build", "form", "construct"],
    "improve": ["enhance", "upgrade", "refine", "strengthen", "optimize"],
    "develop": ["advance", "evolve", "grow", "mature", "progress"],
    "allow": ["permit", "enable", "let", "authorize"],
    "require": ["demand", "necessitate", "mandate", "entail"],
    "provide": ["supply", "offer", "deliver", "furnish", "afford"],
    "include": ["incorporate", "contain", "comprise", "encompass"],
    "consider": ["regard", "deem", "view", "treat", "weigh"],
    "mean": ["signify", "indicate", "imply", "denote", "represent"],
    "become": ["turn", "grow", "develop", "evolve"],
    "remain": ["stay", "persist", "continue", "endure"],
    "continue": ["proceed", "persist", "carry on", "advance"],
    "data": ["information", "records", "metrics", "figures", "statistics"],
    "model": ["system", "framework", "approach", "architecture", "scheme"],
    "privacy": ["confidentiality", "secrecy", "discretion", "anonymity"],
    "security": ["protection", "safety", "safeguarding", "defense"],
    "information": ["data", "details", "facts", "material", "content"],
    "risk": ["hazard", "threat", "danger", "exposure", "peril"],
    "control": ["manage", "govern", "regulate", "oversee", "direct"],
    "process": ["procedure", "method", "operation", "workflow", "routine"],
    "access": ["entry", "admission", "reach", "availability"],
    "cost": ["expense", "price", "outlay", "burden"],
    "benefit": ["advantage", "gain", "profit", "value", "upside"],
    "approach": ["method", "strategy", "tactic", "technique", "route"],
    "directly": ["immediately", "straight", "firsthand", "instantly"],
    "local": ["on-device", "decentralized", "nearby", "resident"],
    "store": ["keep", "retain", "hold", "house", "archive"],
    "process_alt": ["handle", "treat", "work", "run", "execute"],
    "send": ["transmit", "forward", "relay", "dispatch", "convey"],
    "share": ["distribute", "pass", "impart", "hand", "broadcast"],
    "protect": ["safeguard", "defend", "secure", "shield", "preserve"],
    "reduce_alt": ["lower", "cut", "lessen", "trim", "curb"],
    "increase_alt": ["raise", "grow", "boost", "expand", "add"],
    "matter": ["count", "signify", "weigh", "be important"],
    "often": ["frequently", "commonly", "regularly", "typically"],
    "always": ["invariably", "consistently", "constantly", "perpetually"],
    "never": ["nowhere", "at no time"],
    "here": ["in this place", "locally", "on site"],
    "there": ["in that place", "remotely"],
    "now": ["currently", "presently", "at present", "today"],
    "also": ["additionally", "furthermore", "likewise", "moreover"],
    "only": ["merely", "solely", "just", "exclusively"],
    "very": ["extremely", "highly", "exceedingly", "remarkably"],
    "well": ["effectively", "properly", "adequately", "satisfactorily"],
    "however": ["nevertheless", "nonetheless", "yet", "still"],
    "therefore": ["consequently", "thus", "hence", "accordingly"],
    "instead": ["alternatively", "rather", "in place"],
    "because": ["since", "as", "owing to", "given"],
    "about": ["regarding", "concerning", "around", "roughly"],
    "within": ["inside", "inside of", "internal to"],
    "without": ["absent", "lacking", "devoid of"],
    "between": ["among", "amidst", "straddling"],
    "through": ["via", "by means of", "using"],
    "during": ["throughout", "amid", "over the course of"],
    "against": ["versus", "counter to", "opposed to"],
    "among": ["between", "amidst", "surrounded by"],
    "such": ["similar", "like", "of that kind"],
    "this": ["that", "the current", "the present"],
    "that": ["this", "the aforementioned"],
    "these": ["those", "the aforementioned"],
    "their": ["its", "the associated"],
    "our": ["the team's", "the group's"],
}


def coverage(text_tokens: list[str]) -> tuple[int, int]:
    """How many tokens the frequency vocab can substitute for."""
    c = sum(1 for t in text_tokens if t in FREQUENT_VOCAB)
    return c, len(text_tokens)
