"""ΔZ check as a service (C4, 2026-08-13) — removal with receipt.

Contract under test:
- delta_z(): measure mark strength before vs after via detect_multi_key
  registry resolution; delta_z == z_before - z_after exactly (parity);
  removed:true ONLY when the before-state is provable (z>=4) and the
  after-state is not.
- delta_z_transform(): stdlib transforms lifted from
  benchmarks/attack_matrix_v2.py (clean/truncate/shuffle/reformat).
  HONEST measurement: shuffle is the provable removal path (breaks every
  (prev, token) greenlist pair); clean/reformat preserve the mark; truncate
  60% weakens but does NOT break it (documented — no fake removal proof).
- delta_z_report(): optional signed_report (HMAC) attachment.
- CLI ai-wm delta-z: <before> <after> --key OR <file> --transform --key;
  exit 0 on any successful measurement (removed is a FINDING, not an
  error); JSON output; --sign produces a verifiable signed document.
- API POST /api/forensics/delta-z: auth enforced, key secret resolved
  server-side from the registry (never in the body), 401/200 contract.

Reproducible demonstration (seeds documented):
- mark: mark_greenlist(TEXT, KEY, vocab=FREQUENT_VOCAB, seed=0), gamma 0.25
  -> z_before = 13.6083 (watermark_detected)
- shuffle: word shuffle with seed 42 (attack_matrix convention)
  -> z_after = 0.0, delta_z = 13.6083, removed:true
- truncate: first 60% of word tokens -> z_after = 10.8686 (removed:false)
- clean/reformat: mark survives (delta_z = 0.0, removed:false)
- unmarked text: z ~ 0 before AND after -> removed:false (no false receipt)

No data/ writes: core/CLI tests use raw secrets or tmp registries; API tests
monkeypatch the route's registry AND audit logger (audit writes
data/audit.log otherwise).
"""

import json
import os
import subprocess
import sys
from pathlib import Path

import pytest

from ai_watermark_toolkit.forensics.delta_z import (
    TRANSFORM_METHODS,
    delta_z,
    delta_z_report,
    delta_z_transform,
)
from ai_watermark_toolkit.forensics.key_registry import (
    KeyRegistry,
    mask_secret_key_id,
)
from ai_watermark_toolkit.forensics.kgw import mark_greenlist
from ai_watermark_toolkit.forensics.frequent_vocab import FREQUENT_VOCAB
from ai_watermark_toolkit.forensics.signed_report import verify_report

REPO = Path(__file__).resolve().parents[1]
SRC = REPO / "src"

KEY = "demo-kgw-secret-0001"
GAMMA = 0.25

TEXT = (
    "Local AI models are crucial for maintaining user privacy and ensuring "
    "secure interactions with data processing. This reduces the amount of "
    "personal information shared with third parties. On-device processing "
    "keeps sensitive details under your control. The result is a lower risk "
    "of breaches and stronger protection. People gain more confidence when "
    "their data stays local and private systems keep everything on device "
    "without sending anything to remote servers or external infrastructure."
)

UNMARKED = (
    "A normal paragraph about a completely unrelated topic. The weather was "
    "pleasant this morning with a light breeze and clear skies. Several "
    "neighbors walked their dogs along the quiet road. Nothing here was "
    "watermarked or generated by any special method."
)

MARK_SEED = 0      # mark_greenlist seed -> z_before 13.6083 (stable)
SHUFFLE_SEED = 42  # attack_matrix word_shuffle seed


@pytest.fixture(scope="module")
def marked() -> str:
    """Deterministic marked text (seed 0). z_before = 13.6083, >= 4."""
    emb = mark_greenlist(TEXT, KEY, vocab=FREQUENT_VOCAB, seed=MARK_SEED)
    return emb["text"]


def run_cli(args, stdin=None, cwd=None):
    env = dict(os.environ)
    env["PYTHONPATH"] = str(SRC)
    base = [sys.executable, "-m", "ai_watermark_toolkit.cli"]
    return subprocess.run(base + args, capture_output=True, text=True,
                          input=stdin, env=env, cwd=cwd or REPO)


# ---------------------------------------------------------------- core: delta_z
class TestDeltaZCore:
    def test_marked_shuffle_removed(self, marked):
        """The provable removal case: shuffle breaks every greenlist pair."""
        r = delta_z(marked, _shuffle(marked), KEY)
        assert r["verdict_before"] == "watermark_detected"
        assert r["z_before"] >= 4.0, r
        assert r["verdict_after"] != "watermark_detected"
        assert r["z_after"] < 4.0, r
        assert r["removed"] is True, r
        assert r["delta_z"] > 0  # positive delta = mark weakened (z_before - z_after)

    def test_documented_numbers(self, marked):
        """Seeds + expected numbers are part of the contract (reproducibility)."""
        r = delta_z(marked, _shuffle(marked), KEY)
        assert r["z_before"] == pytest.approx(13.6083, abs=1e-3)
        assert r["z_after"] == pytest.approx(0.0, abs=1e-3)
        assert r["delta_z"] == pytest.approx(13.6083, abs=1e-3)
        # P0-4: a raw secret must NEVER surface as key_id — it is masked
        assert r["key_id"] == mask_secret_key_id(KEY)
        assert r["key_id"] != KEY
        assert r["key_source"] == "raw_secret"

    def test_marked_truncate_honest_no_false_removal(self, marked):
        """truncate 60% weakens (delta>0) but does NOT break the mark."""
        r = delta_z_transform(marked, KEY, method="truncate",
                              truncate_fraction=0.6)
        assert r["verdict_before"] == "watermark_detected"
        # the kept (prev, token) chain still carries the mark -> no receipt
        assert r["removed"] is False, r
        assert r["z_after"] >= 4.0, r
        assert r["delta_z"] > 0  # weaker, not removed

    def test_marked_clean_preserves_mark(self, marked):
        """clean = unicode hygiene: tokens untouched -> mark survives."""
        r = delta_z_transform(marked, KEY, method="clean")
        assert r["removed"] is False
        assert r["delta_z"] == pytest.approx(0.0, abs=1e-6)

    def test_marked_reformat_preserves_mark(self, marked):
        r = delta_z_transform(marked, KEY, method="reformat")
        assert r["removed"] is False
        assert r["delta_z"] == pytest.approx(0.0, abs=1e-6)

    def test_unmarked_no_false_removal(self):
        """No provable before-state -> removed:false (no fake receipt)."""
        r = delta_z(UNMARKED, _shuffle(UNMARKED), KEY)
        assert r["verdict_before"] != "watermark_detected"
        assert r["removed"] is False, r
        assert abs(r["z_before"]) < 4.0

    def test_parity_delta_equals_z_before_minus_z_after(self, marked):
        """Spec parity: delta_z == z_before - z_after exactly."""
        for method in ("clean", "truncate", "shuffle", "reformat"):
            r = delta_z_transform(marked, KEY, method=method,
                                  truncate_fraction=0.6)
            assert r["delta_z"] == round(r["z_before"] - r["z_after"], 4), (
                method, r)

    def test_key_id_and_raw_secret_resolution(self, tmp_path):
        """key_id AND raw secret both resolve; same measurement, key_id differs.

        The text is marked with the registry key's OWN secret so detection
        uses the same key material in both resolution paths.
        """
        reg = KeyRegistry(str(tmp_path / "keys.json"))
        reg.add_key({"key_id": "dz-key-1", "family": "kgw",
                     "secret": "dz-secret-1", "gamma": GAMMA})
        emb = mark_greenlist(TEXT, "dz-secret-1", vocab=FREQUENT_VOCAB,
                             seed=MARK_SEED)
        m = emb["text"]
        by_id = delta_z(m, _shuffle(m), "dz-key-1", registry=reg)
        by_secret = delta_z(m, _shuffle(m), "dz-secret-1", registry=reg)
        assert by_id["key_id"] == "dz-key-1"
        assert by_id["key_source"] == "registry"
        # P0-4: the raw secret is MASKED in the reported key_id — same
        # measurement (same key material), no secret in the output
        assert by_secret["key_id"] == mask_secret_key_id("dz-secret-1")
        assert by_secret["key_id"] != "dz-secret-1"
        assert by_secret["key_source"] == "raw_secret"
        assert by_id["z_before"] == by_secret["z_before"]
        assert by_id["z_after"] == by_secret["z_after"]
        assert by_id["removed"] is True
        assert by_secret["removed"] is True

    def test_registry_key_without_secret_raises(self, tmp_path):
        reg = KeyRegistry(str(tmp_path / "keys.json"))
        reg.add_key({"key_id": "nosecret", "family": "kgw"})
        with pytest.raises(ValueError):
            delta_z(TEXT, TEXT, "nosecret", registry=reg)

    def test_unknown_transform_raises(self, marked):
        with pytest.raises(ValueError):
            delta_z_transform(marked, KEY, method="paraphrase")

    def test_transform_result_fields(self, marked):
        r = delta_z_transform(marked, KEY, method="shuffle", seed=SHUFFLE_SEED)
        assert r["method"] == "shuffle"
        assert r["transform_meta"]["seed"] == SHUFFLE_SEED
        assert r["transformed_text_omitted"] is False
        assert r["transformed_text"]  # short text -> included

    def test_transform_methods_constant(self):
        assert TRANSFORM_METHODS == ("clean", "truncate", "shuffle", "reformat")


# ---------------------------------------------------------------- core: report
class TestDeltaZReport:
    def test_unsigned_without_secret(self, marked):
        r = delta_z(marked, _shuffle(marked), KEY)
        out = delta_z_report(r)
        assert out == r
        assert "signature" not in out

    def test_signed_hmac_valid(self, marked):
        r = delta_z(marked, _shuffle(marked), KEY)
        signed = delta_z_report(r, "hmac-secret-1", key_id="dz-key-1")
        sig = signed["signature"]
        assert sig["algorithm"] == "hmac-sha256"
        assert sig["key_id"] == "dz-key-1"
        assert sig["digest"]
        assert verify_report(signed, "hmac-secret-1")["valid"] is True
        assert verify_report(signed, "wrong-secret")["valid"] is False

    def test_signed_input_not_mutated(self, marked):
        r = delta_z(marked, _shuffle(marked), KEY)
        before = dict(r)
        delta_z_report(r, "hmac-secret-1")
        assert r == before


# ---------------------------------------------------------------- CLI
class TestCliDeltaZ:
    def _write(self, tmp_path, name, text):
        f = tmp_path / name
        f.write_text(text, encoding="utf-8")
        return f

    def test_cli_two_files_roundtrip_exit_0(self, tmp_path, marked):
        before = self._write(tmp_path, "before.txt", marked)
        after = self._write(tmp_path, "after.txt", _shuffle(marked))
        r = run_cli(["delta-z", str(before), str(after), "--key", KEY], cwd=tmp_path)
        assert r.returncode == 0, r.stderr
        out = json.loads(r.stdout)
        assert out["removed"] is True
        assert out["z_before"] >= 4.0 and out["z_after"] < 4.0
        assert out["delta_z"] == round(out["z_before"] - out["z_after"], 4)

    def test_cli_transform_single_file_exit_0(self, tmp_path, marked):
        f = self._write(tmp_path, "one.txt", marked)
        r = run_cli(["delta-z", str(f), "--transform", "shuffle", "--key", KEY],
                    cwd=tmp_path)
        assert r.returncode == 0, r.stderr
        out = json.loads(r.stdout)
        assert out["method"] == "shuffle"
        assert out["removed"] is True

    def test_cli_sign_verifiable(self, tmp_path, marked):
        before = self._write(tmp_path, "b.txt", marked)
        after = self._write(tmp_path, "a.txt", _shuffle(marked))
        r = run_cli(["delta-z", str(before), str(after), "--key", KEY,
                     "--sign", "cli-secret-1"], cwd=tmp_path)
        assert r.returncode == 0, r.stderr
        signed = json.loads(r.stdout)
        assert signed["signature"]["algorithm"] == "hmac-sha256"
        assert verify_report(signed, "cli-secret-1")["valid"] is True

    def test_cli_output_file(self, tmp_path, marked):
        before = self._write(tmp_path, "b.txt", marked)
        after = self._write(tmp_path, "a.txt", _shuffle(marked))
        out = tmp_path / "result.json"
        r = run_cli(["delta-z", str(before), str(after), "--key", KEY,
                     "-o", str(out)], cwd=tmp_path)
        assert r.returncode == 0, r.stderr
        assert json.loads(out.read_text(encoding="utf-8"))["removed"] is True

    def test_cli_missing_key_exit_2(self, tmp_path, marked):
        before = self._write(tmp_path, "b.txt", marked)
        after = self._write(tmp_path, "a.txt", _shuffle(marked))
        r = run_cli(["delta-z", str(before), str(after)], cwd=tmp_path)
        assert r.returncode == 2
        assert "--key" in r.stderr

    def test_cli_missing_file_exit_2(self, tmp_path, marked):
        f = self._write(tmp_path, "b.txt", marked)
        r = run_cli(["delta-z", str(f), str(tmp_path / "nope.txt"),
                     "--key", KEY], cwd=tmp_path)
        assert r.returncode == 2
        assert "file not found" in r.stderr.lower()

    def test_cli_transform_with_after_rejected_exit_2(self, tmp_path, marked):
        b = self._write(tmp_path, "b.txt", marked)
        a = self._write(tmp_path, "a.txt", _shuffle(marked))
        r = run_cli(["delta-z", str(b), str(a), "--transform", "shuffle",
                     "--key", KEY], cwd=tmp_path)
        assert r.returncode == 2

    def test_cli_removed_true_still_exit_0(self, tmp_path, marked):
        """The measurement IS the product: removed:true is a finding, not an error."""
        before = self._write(tmp_path, "b.txt", marked)
        after = self._write(tmp_path, "a.txt", _shuffle(marked))
        r = run_cli(["delta-z", str(before), str(after), "--key", KEY],
                    cwd=tmp_path)
        assert r.returncode == 0
        assert json.loads(r.stdout)["removed"] is True


# ---------------------------------------------------------------- API
class TestApiDeltaZ:
    def _client(self, tmp_path, monkeypatch):
        from fastapi.testclient import TestClient
        from ai_watermark_toolkit.api import fastapi_app
        from ai_watermark_toolkit.api.routes import forensics as forensics_route

        reg = KeyRegistry(str(tmp_path / "keys.json"))
        monkeypatch.setattr(forensics_route, "keys", reg)
        # audit writes data/audit.log — silence it (no data/ writes in tests)
        monkeypatch.setattr(forensics_route, "audit",
                            type("DummyAudit", (), {"write": lambda self, p: p})())
        return TestClient(fastapi_app.app)

    def _register(self, client, key_id="dz-api-1", secret=KEY):
        """Register a key whose secret matches the marking key (KEY).

        The API resolves the secret server-side; using the same secret that
        created the mark makes the measurement meaningful (a different key
        would measure z~0 both sides and never show removed:true).
        """
        client.post("/api/forensics/keys",
                    json={"key_id": key_id, "family": "kgw", "secret": secret,
                          "gamma": GAMMA})

    def test_api_two_text_removed(self, tmp_path, monkeypatch, marked):
        c = self._client(tmp_path, monkeypatch)
        self._register(c)
        r = c.post("/api/forensics/delta-z",
                   json={"text_before": marked,
                         "text_after": _shuffle(marked),
                         "key_id": "dz-api-1"})
        assert r.status_code == 200, r.text
        out = r.json()
        assert out["removed"] is True
        assert out["z_before"] >= 4.0 and out["z_after"] < 4.0
        assert "secret" not in json.dumps(out)

    def test_api_transform_mode(self, tmp_path, monkeypatch, marked):
        c = self._client(tmp_path, monkeypatch)
        self._register(c)
        r = c.post("/api/forensics/delta-z",
                   json={"text": marked, "key_id": "dz-api-1",
                         "transform": "shuffle"})
        assert r.status_code == 200, r.text
        out = r.json()
        assert out["method"] == "shuffle"
        assert out["removed"] is True

    def test_api_unknown_key_404(self, tmp_path, monkeypatch, marked):
        c = self._client(tmp_path, monkeypatch)
        r = c.post("/api/forensics/delta-z",
                   json={"text_before": marked, "text_after": marked,
                         "key_id": "nope"})
        assert r.status_code == 404

    def test_api_body_secret_ignored(self, tmp_path, monkeypatch, marked):
        """Secret NEVER in the body: a body secret is ignored; key_id must be registered."""
        c = self._client(tmp_path, monkeypatch)
        r = c.post("/api/forensics/delta-z",
                   json={"text_before": marked, "text_after": marked,
                         "key_id": "dz-api-1", "secret": "forged-in-body"})
        assert r.status_code == 404  # key not registered -> no server-side secret

    def test_api_missing_texts_400(self, tmp_path, monkeypatch):
        c = self._client(tmp_path, monkeypatch)
        self._register(c)
        r = c.post("/api/forensics/delta-z", json={"key_id": "dz-api-1"})
        assert r.status_code == 400

    def test_api_sign_true_signed(self, tmp_path, monkeypatch, marked):
        c = self._client(tmp_path, monkeypatch)
        self._register(c)
        r = c.post("/api/forensics/delta-z",
                   json={"text_before": marked,
                         "text_after": _shuffle(marked),
                         "key_id": "dz-api-1", "sign": True})
        assert r.status_code == 200, r.text
        out = r.json()
        assert out["signature"]["algorithm"] == "hmac-sha256"
        # signed with the key's REGISTRY secret server-side (= KEY here)
        assert verify_report(out, KEY)["valid"] is True

    def test_api_requires_auth(self, tmp_path, monkeypatch, marked):
        from types import SimpleNamespace
        from ai_watermark_toolkit.api.middleware import auth as auth_mod
        c = self._client(tmp_path, monkeypatch)
        self._register(c)
        monkeypatch.setattr(auth_mod, "settings",
                            SimpleNamespace(api_key="test-secret"))
        body = {"text_before": marked, "text_after": _shuffle(marked),
                "key_id": "dz-api-1"}
        r = c.post("/api/forensics/delta-z", json=body)
        assert r.status_code == 401
        r = c.post("/api/forensics/delta-z", json=body,
                   headers={"X-API-Key": "test-secret"})
        assert r.status_code == 200
        assert r.json()["removed"] is True


# ------------------------------------------------------------------ helpers
def _shuffle(text: str, seed: int = SHUFFLE_SEED) -> str:
    """Word shuffle with the attack_matrix seed (42) — deterministic."""
    import random
    rng = random.Random(seed)
    words = text.split()
    rng.shuffle(words)
    return " ".join(words)
