"""Tests for mark_greenlist (the direct impose-greenlist embed path) +
the frequency vocabulary that powers the end-to-end proof (2026-08-13).

These are deterministic and do NOT call Ollama: they prove the marking logic
itself, mirroring what the benchmarks/kgw_e2e_proof.py script does against a
real model.
"""

from ai_watermark_toolkit.forensics.kgw import (
    detect_kgw,
    mark_greenlist,
    tokenize,
)
from ai_watermark_toolkit.forensics.frequent_vocab import FREQUENT_VOCAB, coverage

KEY = "proof-key-1"
WRONG = "proof-key-2"
GAMMA = 0.5


class TestMarkGreenlist:
    def test_marked_text_is_detected(self):
        text = (
            "Local AI models are crucial for maintaining user privacy and "
            "ensuring secure interactions with data processing. This reduces "
            "the amount of personal information shared with third parties. "
            "On-device processing keeps sensitive details under your control. "
            "The result is a lower risk of breaches and stronger protection. "
            "People gain more confidence when their data stays local."
        )
        emb = mark_greenlist(text, KEY, GAMMA, vocab=FREQUENT_VOCAB, seed=42)
        assert emb["replacements"] > 20
        assert emb["green_rate_after"] > 0.7
        r = detect_kgw(emb["text"], KEY, GAMMA)
        assert r["verdict"] == "watermark_detected", r
        assert r["z_score"] >= 4.0

    def test_wrong_key_is_not_detected(self):
        text = (
            "On-device processing keeps personal figures under local control, "
            "reducing the amount of information shared with outside systems. "
            "People gain confidence when their private data stays nearby and "
            "the risk of exposure drops substantially over time."
        )
        emb = mark_greenlist(text, KEY, GAMMA, vocab=FREQUENT_VOCAB, seed=7)
        r = detect_kgw(emb["text"], WRONG, GAMMA)
        assert r["verdict"] != "watermark_detected", r

    def test_control_unmarked_is_clean(self):
        text = (
            "A normal paragraph about a completely unrelated topic. The "
            "weather was pleasant this morning with a light breeze and clear "
            "skies. Several neighbors walked their dogs along the quiet road. "
            "Nothing here was watermarked or generated by any special method."
        )
        r = detect_kgw(text, KEY, GAMMA)
        assert r["verdict"] != "watermark_detected", r

    def test_deterministic_with_seed(self):
        text = "The system processes information locally and keeps control under the user."
        a = mark_greenlist(text, KEY, GAMMA, vocab=FREQUENT_VOCAB, seed=1)
        b = mark_greenlist(text, KEY, GAMMA, vocab=FREQUENT_VOCAB, seed=1)
        assert a["text"] == b["text"]


class TestFrequentVocab:
    def test_coverage_counts(self):
        toks = tokenize("local models protect privacy and data security")
        c, n = coverage(toks)
        assert c > 0
        assert 0 <= c <= n

    def test_vocab_is_substantial(self):
        assert len(FREQUENT_VOCAB) > 100
